// Generated by CoffeeScript 1.8.0
(function() {
  var delay, generator, hold_key, holded_keys, meter, play, play_note, play_notes, playing, playing_timeout_obj, release_holded_keys, start_playing, stop_playing;

  window.keyboard.add_press_action('spacebar', function() {
    stop_playing();
    return start_playing();
  });

  window.keyboard.add_press_handler(function(key_event) {
    if (!(window.keyboard.is_auto_triggered(key_event) || window.keyboard.key_equals(key_event, 'spacebar'))) {
      return stop_playing();
    }
  });

  meter = 0.25;

  holded_keys = '';

  hold_key = function(char) {
    window.keyboard.simulate_keydown(char);
    return holded_keys += char;
  };

  release_holded_keys = function() {
    var k, _i, _len;
    for (_i = 0, _len = holded_keys.length; _i < _len; _i++) {
      k = holded_keys[_i];
      window.keyboard.simulate_keyup(k);
    }
    return holded_keys = '';
  };

  playing = false;

  playing_timeout_obj = null;

  start_playing = function() {
    if (!playing) {
      playing = true;
      meter = parseFloat($('#meter').val());
      window.keyboard.simulate_keydown('S');
      return play(generator($('#score').val()));
    }
  };

  stop_playing = function() {
    if (playing) {
      playing = false;
      window.keyboard.simulate_keyup('S');
      release_holded_keys();
      if (playing_timeout_obj != null) {
        return clearTimeout(playing_timeout_obj);
      }
    }
  };

  play = function(music_box) {
    var note, symbol;
    if (!playing) {
      return;
    }
    symbol = music_box.next();
    switch (symbol) {
      case '|':
      case '\n':
      case ' ':
        return play(music_box);
      case void 0:
        return stop_playing();
      case '{':
        play_notes(((function() {
          var _results;
          _results = [];
          while ((note = music_box.next()) !== '}') {
            _results.push(note);
          }
          return _results;
        })()));
        return delay((function() {
          return play(music_box);
        }), meter);
      default:
        play_note(symbol);
        return delay((function() {
          return play(music_box);
        }), meter);
    }
  };

  play_note = function(note_char) {
    switch (note_char) {
      case '.':
        break;
      default:
        release_holded_keys();
        return hold_key(note_char);
    }
  };

  play_notes = function(note_chars) {
    var n, _i, _len, _results;
    release_holded_keys();
    _results = [];
    for (_i = 0, _len = note_chars.length; _i < _len; _i++) {
      n = note_chars[_i];
      _results.push(hold_key(n));
    }
    return _results;
  };

  generator = function(input_stream) {
    var current;
    current = 0;
    return {
      next: function() {
        return input_stream[current++];
      }
    };
  };

  delay = function(callback, seconds) {
    return playing_timeout_obj = setTimeout(callback, seconds * 1000);
  };

  window.autoplay = {
    start_playing: start_playing,
    stop_playing: stop_playing
  };

}).call(this);
