// Generated by CoffeeScript 1.8.0
(function() {
  var add_press_action, add_press_handler, add_release_action, add_release_handler, get_keycode, is_auto_triggered, key_equals, keycode_map, press_actions, release_actions, simulate_keydown, simulate_keyup, trigger;

  press_actions = {};

  release_actions = {};

  add_press_action = function(key_literal, action) {
    return press_actions[get_keycode(key_literal)] = action;
  };

  add_release_action = function(key_literal, action) {
    return release_actions[get_keycode(key_literal)] = action;
  };

  add_press_handler = function(handler) {
    return $(document).keydown(handler);
  };

  add_release_handler = function(handler) {
    return $(document).keyup(handler);
  };

  $(document).keydown(function(event) {
    var _name;
    return typeof press_actions[_name = event.which] === "function" ? press_actions[_name]() : void 0;
  });

  $(document).keyup(function(event) {
    var _name;
    return typeof release_actions[_name = event.which] === "function" ? release_actions[_name]() : void 0;
  });

  keycode_map = {
    '1': 49,
    '2': 50,
    '3': 51,
    '4': 52,
    '5': 53,
    '6': 54,
    '7': 55,
    '8': 56,
    '9': 57,
    '0': 48,
    '-': 189,
    '=': 187,
    'A': 65,
    'Z': 90,
    'S': 83,
    'X': 88,
    'spacebar': 32,
    'NUM_1': 97,
    'NUM_2': 98,
    'NUM_3': 99,
    'NUM_4': 100,
    'NUM_5': 101,
    'NUM_6': 102,
    'NUM_7': 103,
    'NUM_8': 104,
    'NUM_9': 105,
    'NUM_0': 96,
    'NUM_.': 90,
    'NUM_return': 13,
    'NUM_+': 107,
    'NUM_-': 109,
    'NUM_*': 106,
    'NUM_/': 111
  };

  get_keycode = function(key_literal) {
    return keycode_map[key_literal];
  };

  is_auto_triggered = function(key_event) {
    return key_event.is_auto_triggered;
  };

  key_equals = function(key_event, key_literal) {
    return key_event.which === get_keycode(key_literal);
  };

  simulate_keydown = function(key_literal) {
    return trigger('keydown', get_keycode(key_literal));
  };

  simulate_keyup = function(key_literal) {
    return trigger('keyup', get_keycode(key_literal));
  };

  trigger = function(event_type, which) {
    var e;
    e = jQuery.Event(event_type);
    e.which = which;
    e.is_auto_triggered = true;
    return $(document).trigger(e);
  };

  window.keyboard = {
    add_press_action: add_press_action,
    add_release_action: add_release_action,
    simulate_keydown: simulate_keydown,
    simulate_keyup: simulate_keyup,
    get_keycode: get_keycode,
    key_equals: key_equals,
    is_auto_triggered: is_auto_triggered,
    add_press_handler: add_press_handler,
    add_release_handler: add_release_handler
  };

}).call(this);
