// Generated by CoffeeScript 1.8.0
(function() {
  var add_press_handler, add_release_handler, press_handlers, release_handlers;

  press_handlers = {};

  release_handlers = {};

  $(document).keydown(function(event) {
    var _name;
    if (!event.is_autoplay) {
      window.autoplay.stop_playing();
    }
    return typeof press_handlers[_name = event.which] === "function" ? press_handlers[_name]() : void 0;
  });

  $(document).keyup(function(event) {
    var _name;
    return typeof release_handlers[_name = event.which] === "function" ? release_handlers[_name]() : void 0;
  });

  add_press_handler = function(keycode, handler) {
    return press_handlers[keycode] = handler;
  };

  add_release_handler = function(keycode, handler) {
    return release_handlers[keycode] = handler;
  };

  window.keyboard = {
    add_press_handler: add_press_handler,
    add_release_handler: add_release_handler
  };

}).call(this);
